### ISSUE TITLE
Windows Mixed Reality

### ISSUE THREAD

**Issue by ErrorRaffyline0** [fabianoriccardi/killed-by-microsoft#104]
**What's the Product's Name?**
Windows Mixed Reality
**Describe the product in a single sentence.**
Windows Mixed Reality is/was a component of The Windows Operating System and a series of Windows Mixed Reality headsets that ran Windows Desktop or 3D applications in an immersive VR environment.
**When was the product launched? Provide a specific date, if possible.**
October 17, 2017 (Windows 10 Fall Creators Update)
**When was the product discontinued? Provide a specific date, if possible.**
Deprecated on December 21st, 2023, discontinued on Nov 1st, 2026 (2027 for commercial licenses), removed in a future release of Windows (likely Windows 12).
**What type of product was it? App, Service, OS, or Hardware?**
OS Component and Hardware series

**Comment by fabianoriccardi** [comment]
Added. I will keep only this element about this topic since I have used the term "platform", that can include all compatibility-layers and stores for various devices.

Thanks for the suggestions!
