### ISSUE TITLE
Mixed Reality Portal (App)

### ISSUE THREAD

**Issue by ErrorRaffyline0** [fabianoriccardi/killed-by-microsoft#105]
**What's the Product's Name?**
Mixed Reality Portal
**Describe the product in a single sentence.**
Mixed Reality Portal was/is an app that served as a frontend for Windows Mixed Reality to run apps to run on Windows Mixed Reality headsets, featuring several 3D Home environments.
**When was the product launched? Provide a specific date, if possible.**
October 17, 2017 (Windows 10 Fall Creators Update)
**When was the product discontinued? Provide a specific date, if possible.**
Deprecated on December 21st, 2023, discontinued on Nov 1st, 2026 (2027 for commercial licenses), removed in a future release of Windows (likely Windows 12).
**What type of product was it? App, Service, OS, or Hardware?**
App

**Comment by fabianoriccardi** [comment]
see #104
