### ISSUE TITLE
Windows Mixed Reality for SteamVR

### ISSUE THREAD

**Issue by ErrorRaffyline0** [fabianoriccardi/killed-by-microsoft#106]
**What's the Product's Name?**
Windows Mixed Reality for SteamVR
**Describe the product in a single sentence.**
Windows Mixed Reality for SteamVR was/is a compatibility layer for Windows Mixed Reality that allows Windows Mixed Reality headsets to run SteamVR and use SteamVR games and apps.
**When was the product launched? Provide a specific date, if possible.**
November 15th, 2017
**When was the product discontinued? Provide a specific date, if possible.**
Deprecated on December 21st, 2023, discontinued on Nov 1st, 2026 (2027 for commercial licenses), incompatible with a future release of Windows (likely Windows 12).
**What type of product was it? App, Service, OS, or Hardware?**
App

**Comment by fabianoriccardi** [comment]
see #104
