### ISSUE TITLE
Active Server Pages (ASP)

### ISSUE THREAD

**Issue by cuixiping** [fabianoriccardi/killed-by-microsoft#108]
**What's the Product's Name?**

Active Server Pages (ASP)

**Describe the product in a single sentence.**

Active Server Pages (ASP) is Microsoft's first server-side scripting language and engine for dynamic web pages.

**When was the product launched? Provide a specific date, if possible.**

ASP 1.0 was released in December 1996 as part of IIS 3.0

**When was the product discontinued? Provide a specific date, if possible.**

ASP 3.0 was released in November 2000 as part of IIS 5.0

**What type of product was it? App, Service, OS, or Hardware?**

Web application framework

https://en.wikipedia.org/wiki/Active_Server_Pages

**Comment by fabianoriccardi** [comment]
Hi, as close date I would use the first release of the first version of ASP.NET (2002-01-16), since it became the successor. Thanks for the suggestion!
