### ISSUE TITLE
Support ending for Windows Subsystem for Android (WSA)

### ISSUE THREAD

**Issue by alperenisa** [fabianoriccardi/killed-by-microsoft#109]
Windows Subsystem for Android (WSA)

The Windows for Android subsystem was allowing Windows 11 systems to run Android apps from the Amazon Appstore.

24 June 2021 - at the launch of Windows 11

5 March 2024

App

https://learn.microsoft.com/en-us/windows/android/wsa/

**Comment by fabianoriccardi** [comment]
added! For opening date I refer to [msft blog](https://blogs.windows.com/windowsexperience/2022/02/15/bringing-you-closer-to-what-you-love-with-new-experiences-in-windows-11/).
