### ISSUE TITLE
Microsoft Visual FoxPro

### ISSUE THREAD

**Issue by CarlosTarello** [fabianoriccardi/killed-by-microsoft#11]
**What's the Product's Name?** 
Microsoft Visual FoxPro
-> https://en.wikipedia.org/wiki/Visual_FoxPro

**Describe the product in a single sentence.**
Microsoft Visual FoxPro was a data-centric procedural programming language with object-oriented programming (OOP) features.

**When was the product launched? Provide a specific date, if possible.**
circa 1992

**When was the product discontinued? Provide a specific date, if possible.**
October 16, 2007

**What type of product was it? App, Service, or Hardware?**
Other, like Visual Basic

**Comment by KeyboardG** [comment]
I just had entered the same item. Pasting my details here if it helps.

Visual FoxPro

Visual FoxPro is a procedural and object oriented programming language and database management system.

Launched:
FoxPro Before Microsoft Started in 1984 as FoxBASE.
FoxPro supports MS-DOS in 1986.
Microsoft acquired Fox in 1992 and it becomes a Microsoft product.
Visual FoxPro with Windows controls launched: June 1995

Killed:
Last Update: 10/16/2007
Mainstream End of Support: 01/12/2010

Detailed Timeline: http://www.foxprohistory.org/foxprotimeline.htm

**Comment by fabianoriccardi** [comment]
Thanks to both for the contribution, I will look into the links in the next days!

**Comment by fabianoriccardi** [comment]
fixed https://github.com/fabianoriccardi/killed-by-microsoft/commit/d25c1093205dab4806b2177dee9d7a84e547e18a
