### ISSUE TITLE
Visual Studio App Center is scheduled for retirement on March 31, 2025

### ISSUE THREAD

**Issue by phuongwd** [fabianoriccardi/killed-by-microsoft#111]
**What's the Product's Name?**
Visual Studio App Center

**Describe the product in a single sentence.**
Integrated developer services for building, testing, releasing, and monitoring mobile and desktop apps

**When was the product launched? Provide a specific date, if possible.**
Since 2017

**When was the product discontinued? Provide a specific date, if possible.**
March 31, 2025

**What type of product was it? App, Service, OS, or Hardware?**
Service

**Comment by fabianoriccardi** [comment]
Added, thanks for the contribution!
