### ISSUE TITLE
Wiki for MS Teams

### ISSUE THREAD

**Issue by laenan8466** [fabianoriccardi/killed-by-microsoft#112]
**What's the Product's Name?**
[Wiki for MS Teams/Sharepoint](https://techcommunity.microsoft.com/t5/microsoft-teams-public-preview/now-in-public-preview-future-of-wiki-and-notes-in-teams/td-p/3780747)

**Describe the product in a single sentence.**
A simple and effective Wikipedia in MS Teams & Sharepoint.

**When was the product launched? Provide a specific date, if possible.**
Short web search didn‘t gave informations

**When was the product discontinued? Provide a specific date, if possible.**
01/2024

**What type of product was it? App, Service, OS, or Hardware?**
Service/Feature in MS Teams

**Comment by fabianoriccardi** [comment]
Added, thanks for the contribution!
