### ISSUE TITLE
Microsoft Publisher

### ISSUE THREAD

**Issue by mhdfrsfrhn** [fabianoriccardi/killed-by-microsoft#113]
**What's the Product's Name?**
Microsoft Publisher

**Describe the product in a single sentence.**
Microsoft Publisher is a desktop publishing application from Microsoft, differing from Microsoft Word in that the emphasis is placed on page layout and graphic design rather than text composition and proofreading.

**When was the product launched? Provide a specific date, if possible.**
1991

**When was the product discontinued? Provide a specific date, if possible.**
October 2026

**What type of product was it? App, Service, OS, or Hardware?**
App

**Comment by n2uts** [comment]
link:
https://support.microsoft.com/en-us/office/microsoft-publisher-will-no-longer-be-supported-after-october-2026-ee6302a2-4bc7-4841-babf-8e9be3acbfd7

**Comment by fabianoriccardi** [comment]
Added, thanks for the contribution!
