### ISSUE TITLE
Microsoft Content Management Server

### ISSUE THREAD

**Issue by damieng** [fabianoriccardi/killed-by-microsoft#115]
**What's the Product's Name?**

Microsoft Content Management Server

**Describe the product in a single sentence.**

A web based content management system for use by authors, editors, moderators, developers and designers to prepare and publish web-based content.

**When was the product launched? Provide a specific date, if possible.**

January 2002.

**When was the product discontinued? Provide a specific date, if possible.**

April 14, 2009,

**What type of product was it? App, Service, OS, or Hardware?**

App

**Comment by fabianoriccardi** [comment]
Added, thanks for the contribution!
