### ISSUE TITLE
"choice failures", "mergers" and "acquisitions" by Microsoft?

### ISSUE THREAD

**Issue by ghost** [fabianoriccardi/killed-by-microsoft#116]

**Comment by fabianoriccardi** [comment]
Wunderlist is already there; Nokia is still alive, but the brand Lumia is already in the graveyard; Android for Windows was just inserted. 

I can't find anything about nextbase.

**Comment by fabianoriccardi** [comment]
I was searching NextBase as a software, not a company, sorry. In general, I would leave out the killed companies, since the graveyard is already crowed by products.
