### ISSUE TITLE
TakeLessons

### ISSUE THREAD

**Issue by aymak91** [fabianoriccardi/killed-by-microsoft#118]
**What's the Product's Name?**
TakeLessons.com

**Describe the product in a single sentence.**
TakeLessons was a platform for freelance teachers to connect with students.

**When was the product launched? Provide a specific date, if possible.**
2008
source: https://www.crunchbase.com/organization/takelessons-com

**When was the product discontinued? Provide a specific date, if possible.**
November 15, 2024. As of Aug 16, new students will no longer be able to connect with teachers.
https://learn.microsoft.com/en-us/takelessons/takelessons-closure-faq

**What type of product was it? App, Service, OS, or Hardware?**
Service

**Comment by fabianoriccardi** [comment]
Added, thanks for the contribution!
