### ISSUE TITLE
MSN Spaces

### ISSUE THREAD

**Issue by lordfeck** [fabianoriccardi/killed-by-microsoft#12]
**What's the Product's Name?**
MSN Spaces

**Describe the product in a single sentence.**
A highly customisable blogging and social networking platform that integrated closely with MSN Messenger. It was eventually rebranded as Windows Live Spaces before being discontinued in 2011.

**When was the product launched? Provide a specific date, if possible.**
2004

**When was the product discontinued? Provide a specific date, if possible.**
2011

**What type of product was it? App, Service, or Hardware?**
Service

More info: https://microsoft.fandom.com/wiki/Windows_Live_Spaces

**Comment by fabianoriccardi** [comment]
added https://github.com/fabianoriccardi/killed-by-microsoft/commit/b2d6e77f25482387a12bf32ddbf65f60f62498f2 

Thank you for the contribution!
