### ISSUE TITLE
Remove Team Live Events

### ISSUE THREAD

**Issue by Planefly1000** [fabianoriccardi/killed-by-microsoft#121]
Team live events will not discontinued on September 2024. As shown in https://learn.microsoft.com/en-us/microsoftteams/teams-live-events/what-are-teams-live-events showing note that Teams live events are no longer going away on September 30, 2024. While we still recommend you to upgrade to Teams town hall when ready to take advantage of new features and experiences, your users can continue to schedule events beyond September 2024. For more information, see Updates for Town Hall in Microsoft Teams and Teams Live Events.

**Comment by fabianoriccardi** [comment]
This was a saving in extremis, thank for the notification!
