### ISSUE TITLE
Add Calendar

### ISSUE THREAD

**Issue by Planefly1000** [fabianoriccardi/killed-by-microsoft#122]
**What's the Product's Name?**
Calendar
**Describe the product in a single sentence.**
Calender is a personal calendar application made by Microsoft for Microsoft Windows and was included from Windows Vista to Windows 11. It offers synchronization of calendars using Microsoft Exchange Server, Outlook.com, Apple's iCloud calendar service, and Google Calendar.
**When was the product launched? Provide a specific date, if possible.**
2014
**When was the product discontinued? Provide a specific date, if possible.**
December 31 2024
**What type of product was it? App, Service, OS, or Hardware?**
App

**Comment by fabianoriccardi** [comment]
Great thank again! Added in 8b73cc2b0fa94585f0b8d2cfbf777a3de5ead065. Also, I have added also the companion People app.
