### ISSUE TITLE
Add Azure Kinect

### ISSUE THREAD

**Issue by Planefly1000** [fabianoriccardi/killed-by-microsoft#123]
**What's the Product's Name?**
Azure Kinect
**Describe the product in a single sentence.**
Azure Kinect was a developer kit and PC peripheral which employs the use of artificial intelligence sensors for computer vision and speech models, and is connected to the Microsoft Azure cloud. It is the successor to the Microsoft Kinect line of sensors.
**When was the product launched? Provide a specific date, if possible.**
March 2020
**When was the product discontinued? Provide a specific date, if possible.**
October 2023
**What type of product was it? App, Service, OS, or Hardware?**
Hardware

**Comment by fabianoriccardi** [comment]
I was checking the date, and I find out that maybe wiki is wrong. On Azure website the release date is 2019-06-15 https://azure.microsoft.com/it-it/updates/azure-kinect-dk-is-now-generally-available-in-the-united-states-and-china/ 

What do you think?

**Comment by Planefly1000** [comment]
Oh! So set date to 2019

**Comment by Planefly1000** [comment]
But This webpage shows that this was launched in July. But 2019-6-15 Shows June 15 2019. But launched on July 15 2019

**Comment by fabianoriccardi** [comment]
I keep 2019-07-15... Who am I to disagree with the news officially reported on Azure website?

**Comment by fabianoriccardi** [comment]
Added!
