### ISSUE TITLE
Mono

### ISSUE THREAD

**Issue by Rosentti** [fabianoriccardi/killed-by-microsoft#126]
**What's the Product's Name?**
Mono

**Describe the product in a single sentence.**
Discontinued cross-platform C# runtime, superceded by .NET Core, with it's remains being transferred to the Wine project. 

**When was the product launched? Provide a specific date, if possible.**
June 30, 2004

**When was the product discontinued? Provide a specific date, if possible.**
August 27, 2024

**What type of product was it? App, Service, OS, or Hardware?**
App

Mono is used by a bunch of major apps, like Unity. Mono development has been discontinued for a while now, but this effectively marks the end of support officially. There's some sort of "newer Mono", which you can find info about here: https://www.mono-project.com/

**Comment by fabianoriccardi** [comment]
Hi, did you think that Wine will continue to develop it?

**Comment by Planefly1000** [comment]
Do you think that Mono is discontinued? After reading this, Wine acquired Mono. So wine will continue to develop Mono or not?

**Comment by fabianoriccardi** [comment]
Looking at the current official [repository](https://gitlab.winehq.org/mono/mono), it seems not dead. So, Microsoft didn't kill the Mono. Of course, since .NET is now cross-platform, it will move in a secondary position.

If you think this is wrong, let me know.
