### ISSUE TITLE
Change link of TakeLesson

### ISSUE THREAD

**Issue by Planefly1000** [fabianoriccardi/killed-by-microsoft#128]
Please change link of Takelessons from Crushbase to Wikipedia.
Link–https://en.m.wikipedia.org/wiki/TakeLessons

**Comment by fabianoriccardi** [comment]
Thanks, for sure this is a better reference! [d106967](https://github.com/fabianoriccardi/killed-by-microsoft/commit/d10696716d6264c55248495b0c592cb02ec97c50)
