### ISSUE TITLE
Add Wordpad

### ISSUE THREAD

**Issue by Planefly1000** [fabianoriccardi/killed-by-microsoft#129]
**What's the Product's Name?**
WordPad
**Describe the product in a single sentence.**
WordPad is a word processor included with Windows 95 and later.
**When was the product launched? Provide a specific date, if possible.**
 August 24, 1995
**When was the product discontinued? Provide a specific date, if possible.**
With the release of Windows 11, 24H2
**What type of product was it? App, Service, OS, or Hardware?**
App.

**Comment by Planefly1000** [comment]
Uhhh.... Could you please change Italian Wikipedia to English Wikipedia

**Comment by fabianoriccardi** [comment]
Opss.. Corrected!
