### ISSUE TITLE
Onfolio

### ISSUE THREAD

**Issue by pmdci** [fabianoriccardi/killed-by-microsoft#16]
See:
https://en.wikipedia.org/wiki/Windows_Live_Toolbar#Onfolio

Onfolio was an online research tool which could be used as a reference manager. Microsoft bought it and killed it a few months later.

**Comment by fabianoriccardi** [comment]
added! https://github.com/fabianoriccardi/killed-by-microsoft/commit/5e9a6db5b3db7d54b37aee040fd3c6aac37bfe72

About Expressio Studio, it is already in the greveyard, I don't think I will add all the apps that composed the suite.

Thanks for all the contributions!
