### ISSUE TITLE
Office remote

### ISSUE THREAD

**Issue by likelieke** [fabianoriccardi/killed-by-microsoft#17]
I have no idea how to find the open and closing date but i still grieve for office remote and love to have a gravestone to commemorate it. But I'm not quite sure if this counts as it still technically still available on windows phone.
```
  {
    "dateClose": "YYYY-MM-DD",
    "dateOpen": "YYYY-MM-DD",
    "description": "Office remote was a way to control Office products such as PowerPoint, Word and Excel from a Windows or Android phone.",
    "link": "https://web.archive.org/web/20150421030104/https://play.google.com/store/apps/details?id=com.microsoft.office.officeremote",
    "links": [
      "https://web.archive.org/web/20210516221455/https://support.microsoft.com/en-us/topic/office-remote-for-pc-7e3d9342-61c7-4bc2-8bc0-fa47542d1bce",
      "https://www.microsoft.com/en-us/p/office-remote/9wzdncrfhx5h"
    ]
    "name": "Office remote",
    "type": "app"
  }
```

The app store link is dead so i added an archive link. And the official documentation also looks to be gone soon as it says that it will be removed shortly so I've also added an archive link for that.

I'll make a pull request if you can explain what to do with the unknown dates.

**Comment by fabianoriccardi** [comment]
added! https://github.com/fabianoriccardi/killed-by-microsoft/commit/4cef264249448f0c74bb514b02b4446c1e5525cb

I prefer to use the link to wikipedia whenever available (which also provides begin and close dates).

Thanks for the contribution!
