### ISSUE TITLE
Sidewinder

### ISSUE THREAD

**Issue by natelaff** [fabianoriccardi/killed-by-microsoft#18]
**What's the Product's Name?**
Sidewinder game hardware

**Describe the product in a single sentence.**
Gaming hardware-- joysticks, driving wheels, game controllers, and GameTalk chat hardware

**When was the product launched? Provide a specific date, if possible.**
95?

**When was the product discontinued? Provide a specific date, if possible.**

**What type of product was it? App, Service, or Hardware?**
Hardware

**Comment by joshuachung** [comment]
[https://en.wikipedia.org/wiki/Microsoft_SideWinder](url)

**Comment by fabianoriccardi** [comment]
Added! https://github.com/fabianoriccardi/killed-by-microsoft/commit/4cef264249448f0c74bb514b02b4446c1e5525cb

Thanks for the contribution!
