### ISSUE TITLE
Fingerprint reader

### ISSUE THREAD

**Issue by natelaff** [fabianoriccardi/killed-by-microsoft#19]
**What's the Product's Name?**
Microsoft Fingerprint Reader

**Describe the product in a single sentence.**
USB Fingerprint reader to unlock PC and certain apps.

**When was the product launched? Provide a specific date, if possible.**
XP SP2 I think

**When was the product discontinued? Provide a specific date, if possible.**
They discontinued it when Vista came out. Never released drivers for VIsta

**What type of product was it? App, Service, or Hardware?**
Hardware

**Comment by fabianoriccardi** [comment]
added https://github.com/fabianoriccardi/killed-by-microsoft/commit/85c6b67a6612687985be31eff276f5b4c4f75eb3

Thanks for the contribution!
