### ISSUE TITLE
Broadband networking

### ISSUE THREAD

**Issue by natelaff** [fabianoriccardi/killed-by-microsoft#20]
**What's the Product's Name?**
Broadband networking

**Describe the product in a single sentence.**
Broadband networking hardware, a wireless router and NIC

**When was the product launched? Provide a specific date, if possible.**

**When was the product discontinued? Provide a specific date, if possible.**

**What type of product was it? App, Service, or Hardware?**
Hardware

**Comment by fabianoriccardi** [comment]
Added https://github.com/fabianoriccardi/killed-by-microsoft/commit/85c6b67a6612687985be31eff276f5b4c4f75eb3

Thanks for the contribution!
