### ISSUE TITLE
Is it fair to say Microsoft killed Silverlight?

### ISSUE THREAD

**Issue by AshleighAdams** [fabianoriccardi/killed-by-microsoft#23]
Silverlight was killed by browsers/Apple dropping the plugin architecture. I personally wouldn't say a product becoming obsolete is the same as it being killed by its author/owner.

**Comment by Yoroion** [comment]
I agree with you too.

**Comment by fabianoriccardi** [comment]
>  I personally wouldn't say a product becoming obsolete is the same as it being killed by its author/owner.

I agree, but sometimes the line between killing a product and letting it die is very thin. Even if it is not the case with Silverlight, I don't like to leave it out, since it is a historical and very debated software. Maybe I could add a quick note below its description...
