### ISSUE TITLE
Windows Live OneCare

### ISSUE THREAD

**Issue by miguedevel** [fabianoriccardi/killed-by-microsoft#25]
**What's the Product's Name?**
Windows Live OneCare
**Describe the product in a single sentence.**
A computer security and performance enhancement service for Windows, incorporating an anti-virus, firewall and more.
**When was the product launched? Provide a specific date, if possible.**
May 31 2005
**When was the product discontinued? Provide a specific date, if possible.**
June 30 2009
**What type of product was it? App, Service, or Hardware?**
App, service.

More info here: https://en.wikipedia.org/wiki/Windows_Live_OneCare

**Comment by fabianoriccardi** [comment]
Added as app https://github.com/fabianoriccardi/killed-by-microsoft/commit/85c6b67a6612687985be31eff276f5b4c4f75eb3

Thanks for the contribution!
