### ISSUE TITLE
Microsoft SPOT (Smart Personal Objects Technology)

### ISSUE THREAD

**Issue by wocko1** [fabianoriccardi/killed-by-microsoft#26]
**What's the Product's Name?**
Microsoft Smart Personal Objects Technology
**Describe the product in a single sentence.**
An early smartwatch and other products that received information broadcasts via FM radio waves
**When was the product launched? Provide a specific date, if possible.**
2004
**When was the product discontinued? Provide a specific date, if possible.**
January 1 2012
**What type of product was it? App, Service, or Hardware?**
Hardware & Service

**Comment by fabianoriccardi** [comment]
Added https://github.com/fabianoriccardi/killed-by-microsoft/commit/85c6b67a6612687985be31eff276f5b4c4f75eb3

Thanks for the suggestion!
