### ISSUE TITLE
WebTV/MSN TV

### ISSUE THREAD

**Issue by wocko1** [fabianoriccardi/killed-by-microsoft#27]
**What's the Product's Name?**
WebTV (later MSN TV)
**Describe the product in a single sentence.**
A set top box that allowed people to browse the internet on a television set.
**When was the product launched? Provide a specific date, if possible.**
September 1996
**When was the product discontinued? Provide a specific date, if possible.**
September 30, 2013,
**What type of product was it? App, Service, or Hardware?**
Hardware & Service

**Comment by fabianoriccardi** [comment]
Added as service https://github.com/fabianoriccardi/killed-by-microsoft/commit/85c6b67a6612687985be31eff276f5b4c4f75eb3

If I understand correctly, the hardware was designed to support MSN TV and a few other services (email and internet browsing). Moreover, many manufacturers launched their hardware clients supporting this service (products are listed on the wiki page), but I don't see a specific item produced by Microsoft. 

Thanks for the contribution!
