### ISSUE TITLE
EdgeHTML was not cross platform

### ISSUE THREAD

**Issue by arye-eidelman** [fabianoriccardi/killed-by-microsoft#29]
> ### Microsoft Edge (EdgeHTML)
> Microsoft Edge is a cross-platform web browser

EdgeHTML was not cross platform. Edge used the native browser engine (Safari, Chrome) for it's mobile apps until it switched to chromium. It was also not available on many platforms (Windows 7, 8, macOS, Linux) until the switch.

Cross-platform was one of the benefits of ditching edgeHTML for chromium.

**Comment by fabianoriccardi** [comment]
fixed!
