### ISSUE TITLE
Digital Sound System 80

### ISSUE THREAD

**Issue by PrdAmrican** [fabianoriccardi/killed-by-microsoft#33]
What's the Product's Name?
Digital Sound System 80
Describe the product in a single sentence.
A three piece digital audio system
When was the product launched? Provide a specific date, if possible.
1998
When was the product discontinued? Provide a specific date, if possible.
A few yeas later.  No sure exactly.
What type of product was it? App, Service, or Hardware?
Hardware

**Comment by PrdAmrican** [comment]
Used one of these for several years until the woofer crapped out.

**Comment by fabianoriccardi** [comment]
Added https://github.com/fabianoriccardi/killed-by-microsoft/commit/8cf5a4d4f5af7ab573db188cbfb42c191a7c2c92

 I found in an old forum that it was already discontinued in 2000...
