### ISSUE TITLE
Microsoft Cordless Phone System MP-900

### ISSUE THREAD

**Issue by PrdAmrican** [fabianoriccardi/killed-by-microsoft#34]
**What's the Product's Name?**
Microsoft Cordless Phone System MP-900
**Describe the product in a single sentence.**
Personal Home Phone system, PC based (Win95 thru WinXP) with voice mail system and 900MHz wireless phone
**When was the product launched? Provide a specific date, if possible.**
1998
**When was the product discontinued? Provide a specific date, if possible.**
2000-ish... would not work on WinME (then what did?)
**What type of product was it? App, Service, or Hardware?**
hardware

**Comment by fabianoriccardi** [comment]
added https://github.com/fabianoriccardi/killed-by-microsoft/commit/8cf5a4d4f5af7ab573db188cbfb42c191a7c2c92

Even this product lasted about year..
