### ISSUE TITLE
TouchDevelop

### ISSUE THREAD

**Issue by sent44** [fabianoriccardi/killed-by-microsoft#36]
**What's the Product's Name?**
TouchDevelop

**Describe the product in a single sentence.**
The educational platform that teach coding for kid, cross-platform but work very well on mobile. Discontinued for MakeCode.
~But MakeCode doesn't have custom keyboard for easy coding on mobile like TouchDevelop has. It make thing easy to prototype/test algorithm when I am not use computer.~

**When was the product launched? Provide a specific date, if possible.**
Maybe [July 20, 2011](https://www.microsoft.com/en-us/research/project/touchdevelop/)

**When was the product discontinued? Provide a specific date, if possible.**
[June 22, 2019](https://github.com/microsoft/TouchDevelop/blob/c0797dd54d1107bbef4e9f7f58e9723ee68ad7b3/editor/hub.ts#L1571)

**What type of product was it? App, Service, or Hardware?**
Web app?

**Comment by fabianoriccardi** [comment]
Added! https://github.com/fabianoriccardi/killed-by-microsoft/commit/75983e1bad096a83e19d21f7f1d560d40b92ff11

Thanks for the contribution! Finding the closing date directly in the repo is impressive :)
