### ISSUE TITLE
Microsoft PictureIt!

### ISSUE THREAD

**Issue by gordonfreesonos** [fabianoriccardi/killed-by-microsoft#37]
Microsoft PictureIt!

Easy to use photo editing application

September 1996

2006

App

https://en.wikipedia.org/wiki/Microsoft_Picture_It!

**Comment by fabianoriccardi** [comment]
Added https://github.com/fabianoriccardi/killed-by-microsoft/commit/a7c5ee6679ce90ff7607f714c5992037b2b31774

Thanks for the contribution!
