### ISSUE TITLE
Windows Live Mesh

### ISSUE THREAD

**Issue by adamzea** [fabianoriccardi/killed-by-microsoft#39]
Windows Live Mesh

A web-based application desktop environment with file syncing.

2008-2011

App & Service

https://en.wikipedia.org/wiki/Windows_Live_Mesh

**Comment by dmackca** [comment]
And before that, FolderShare!

**Comment by fabianoriccardi** [comment]
Added https://github.com/fabianoriccardi/killed-by-microsoft/commit/a7c5ee6679ce90ff7607f714c5992037b2b31774

Thanks for the contribution!
