### ISSUE TITLE
MSN Chat

### ISSUE THREAD

**Issue by nvx** [fabianoriccardi/killed-by-microsoft#41]
**What's the Product's Name?**
MSN Chat

**Describe the product in a single sentence.**
A chat service that followed after Comic Chat.

**When was the product launched? Provide a specific date, if possible.**
~1999 (https://www.wintersnet.net/history.php)

**When was the product discontinued? Provide a specific date, if possible.**
2006-10-16 (https://web.archive.org/web/20061009052049/http://groups.msn.com/Editorial/en-gb/Content/chat.htm)

**What type of product was it? App, Service, or Hardware?**
Service

**Comment by fabianoriccardi** [comment]
Thanks for the suggestion! It would use "MSN Chat was the Microsoft Network version of IRCX (Internet Relay Chat extensions), which replaced Microsoft Chat." as description... What do you think?

**Comment by fabianoriccardi** [comment]
Added https://github.com/fabianoriccardi/killed-by-microsoft/commit/d9b5026966d46d73541c1146f54eb339817ed774

if you have any other suggestion, let me know!
