### ISSUE TITLE
DriveSpace aka DoubleSpace

### ISSUE THREAD

**Issue by IceCubeDocOc** [fabianoriccardi/killed-by-microsoft#42]
The purpose of DriveSpace is to increase the amount of data the user could store on disks by transparently compressing and decompressing data on-the-fly.
Started with DOS 6 and died with XP
Competition for this product was STACKER.

**Comment by fabianoriccardi** [comment]
Added https://github.com/fabianoriccardi/killed-by-microsoft/commit/d9b5026966d46d73541c1146f54eb339817ed774

thanks for the suggestion!
