### ISSUE TITLE
Games for Windows – LIVE

### ISSUE THREAD

**Issue by wTonyChen** [fabianoriccardi/killed-by-microsoft#46]
**What's the Product's Name?**
Games for Windows – LIVE

**Describe the product in a single sentence.**
An online gaming service for Windows

**When was the product launched? Provide a specific date, if possible.**
May 29, 2007

**When was the product discontinued? Provide a specific date, if possible.**
15 August 2013

**What type of product was it? App, Service, or Hardware?**
Service

**Comment by fabianoriccardi** [comment]
Thanks for the suggestion!

added https://github.com/fabianoriccardi/killed-by-microsoft/commit/d9b5026966d46d73541c1146f54eb339817ed774
