### ISSUE TITLE
3D Movie Maker

### ISSUE THREAD

**Issue by mateusza** [fabianoriccardi/killed-by-microsoft#48]
**What's the Product's Name?**

3D Movie Maker

**Describe the product in a single sentence.**

Children program to make films by animating 3D characters.

**When was the product launched? Provide a specific date, if possible.**

Around 1995

**When was the product discontinued? Provide a specific date, if possible.**

It was a single release in 1995 and a few themed editions. None of editions was ever continued.

**What type of product was it? App, Service, or Hardware?**

Windows 95 application.

https://en.wikipedia.org/wiki/3D_Movie_Maker

**Comment by fabianoriccardi** [comment]
Thanks for the suggestion!

Added here https://github.com/fabianoriccardi/killed-by-microsoft/commit/d9b5026966d46d73541c1146f54eb339817ed774

**Comment by mateusza** [comment]
They just resurrected it! https://www.windowscentral.com/nerd-sniping-convinces-microsoft-open-source-3d-movie-maker-1995

https://github.com/microsoft/Microsoft-3D-Movie-Maker

**Comment by fabianoriccardi** [comment]
Incredible 😂 however I would leave it as dead, the repository is published as "archived" and unsupported.

**Comment by mateusza** [comment]
That's right! But maybe - in future - you could add some indication of projects that were released as open-source etc. Maybe they will do it again with other ones?

**Comment by fabianoriccardi** [comment]
> Maybe they will do it again with other ones?

Probably yes, I think that WPF and Winform are examples of this: they were released as open-source to avoid the complete and fast discontinuation.

> But maybe - in future - you could add some indication of projects that were released as open-source etc

Nice idea, I will consider it!
