### ISSUE TITLE
Microsoft Proxy,  ISA Server or Forefront TMG 

### ISSUE THREAD

**Issue by doensko** [fabianoriccardi/killed-by-microsoft#49]
Microsoft ISA Server or Forefront TMG 

Microsoft Proxy Server v2.0 was launched in December 1997

support ceased on 14 April 2015 and extended support has ended on 14 April 2020.

App

**Comment by fabianoriccardi** [comment]
Added https://github.com/fabianoriccardi/killed-by-microsoft/commit/5a69b2aa9cd9173335d986d01564946b0715c1a6

As open date, I have used the launch of Microsoft Proxy Server v1

Thanks for the contribution!
