### ISSUE TITLE
Various Xbox Games that were showcased then never released

### ISSUE THREAD

**Issue by CartBlanche** [fabianoriccardi/killed-by-microsoft#5]
**Xbox Games**
Scalebound
But there are more, just can't think of them right now.

[Scalebound](https://en.m.wikipedia.org/wiki/Scalebound#cite_note-6) is a cancelled [action role-playing game](https://en.m.wikipedia.org/wiki/Action_role-playing_game) being developed by [PlatinumGames](https://en.m.wikipedia.org/wiki/PlatinumGames) from 2013 to 2017. It was scheduled to be released in 2017 for [Xbox One](https://en.m.wikipedia.org/wiki/Xbox_One) and [Microsoft Windows](https://en.m.wikipedia.org/wiki/Microsoft_Windows), but [Microsoft Studios](https://en.m.wikipedia.org/wiki/Microsoft_Studios) announced the cancellation of the game's development in January 2017.

**What type of product was it? App, Service, or Hardware?**
Game/App

**Comment by fabianoriccardi** [comment]
> But there are more, just can't think of them right now.

I know, the amount of dead projects is uncountable, it will take time to add even a small part of them.

**Comment by fabianoriccardi** [comment]
I read better the history of this project, it seems it was never released, I'm notsure if it should be included in this list. Moreover, [recent news](https://www.videogameschronicle.com/news/hideki-kamiya-says-hes-totally-serious-about-resurrecting-xbox-exclusive-scalebound/) suggest a possible reboot of the project.
