### ISSUE TITLE
Microsoft SharePoint Designer

### ISSUE THREAD

**Issue by doensko** [fabianoriccardi/killed-by-microsoft#50]
Microsoft SharePoint Designer

Discontinued HTML editor freeware for creating or modifying Microsoft SharePoint sites

Launched: November 30, 2006

On October 30, 2012, Microsoft released SharePoint Designer 2013.[4] This is the last version of SharePoint Designer.

App

**Comment by fabianoriccardi** [comment]
Added https://github.com/fabianoriccardi/killed-by-microsoft/commit/aaf1ed891881a8fce98ddc7051a52b085721eee1

Thanks for the contribution!
