### ISSUE TITLE
Visual Foxpro

### ISSUE THREAD

**Issue by ziobillj** [fabianoriccardi/killed-by-microsoft#51]
Microsoft Visual FoxPro

**Describe the product in a single sentence.**
DBMS based on the dBase programming language
**When was the product launched? Provide a specific date, if possible.**
1984 (Microsoft from 1992)
**When was the product discontinued? Provide a specific date, if possible.**
March 2007
**What type of product was it? App, Service, or Hardware?**
App

**Comment by SeregaKR** [comment]
Not quite correct. The extended support ended on 13.01.2015. The last version was **VFP 9 SP2 with Hotfixes** - v. 09.00.0000.7423 on 3.04.2009

**Comment by fabianoriccardi** [comment]
Sorry for the long delay, I have added it. However I'm not sure about the closing date. @SeregaKR do you have a link? I have only found this https://support.microsoft.com/en-us/topic/fix-the-group-header-of-a-data-grouping-is-not-printed-at-the-top-of-a-page-as-expected-after-you-install-visual-foxpro-9-0-service-pack-2-756c2270-7d55-0df8-88c4-e5307ddebf05
that reports 23-Feb-2009

**Comment by SeregaKR** [comment]
https://docs.microsoft.com/en-us/lifecycle/products/microsoft-visual-foxpro-90 here it is

**Comment by fabianoriccardi** [comment]
Suggestion accepted!
