### ISSUE TITLE
Visual J#

### ISSUE THREAD

**Issue by VSpike** [fabianoriccardi/killed-by-microsoft#52]
**What's the Product's Name?**
Visual J Sharp (J#)

**Describe the product in a single sentence.**
A programming language and development tooling which was meant to help Java developers move to the .NET ecosystem. 

**When was the product launched? Provide a specific date, if possible.**
2002

**When was the product discontinued? Provide a specific date, if possible.**
2007

**What type of product was it? App, Service, or Hardware?**
Programming language/Compiler

**Comment by fabianoriccardi** [comment]
Added https://github.com/fabianoriccardi/killed-by-microsoft/commit/859dfc526c4e290a914e0796984e866a1dcaa58b
