### ISSUE TITLE
Visual J++

### ISSUE THREAD

**Issue by VSpike** [fabianoriccardi/killed-by-microsoft#53]
**What's the Product's Name?**
Microsoft Visual J++

**Describe the product in a single sentence.**
Microsoft's own implementation of Java which ran only on their JVM (MSJVM) and whilst conforming to the Java language specification omitted some features and added some additional extentions.

**When was the product launched? Provide a specific date, if possible.**
1996

**When was the product discontinued? Provide a specific date, if possible.**
2004

**What type of product was it? App, Service, or Hardware?**
Programming language/compiler

**Comment by fabianoriccardi** [comment]
Added https://github.com/fabianoriccardi/killed-by-microsoft/commit/859dfc526c4e290a914e0796984e866a1dcaa58b.

Thanks for the contribution!
