### ISSUE TITLE
Microsoft Tay (AI bot)

### ISSUE THREAD

**Issue by w01w13** [fabianoriccardi/killed-by-microsoft#54]
Describe the product in a single sentence.

Probably the fastest death in list, was taken down after 16 hours when the AI started to tweet inappropriate tweets

https://en.m.wikipedia.org/wiki/Tay_(bot)

When was the product launched? Provide a specific date, if possible.
March 23 2016 

When was the product discontinued? Provide a specific date, if possible.
March 24 2016

What type of product was it? App, Service, or Hardware?
Sortware, AI bot

**Comment by fabianoriccardi** [comment]
This was a pearl! 😂 Added in https://github.com/fabianoriccardi/killed-by-microsoft/commit/8ddf8053b3671d2f9d64b840ec0fd553f49fe15e

Thanks for the contribution!
