### ISSUE TITLE
Microsoft Actimates Barney

### ISSUE THREAD

**Issue by ongbh** [fabianoriccardi/killed-by-microsoft#56]
**What's the Product's Name?** Microsoft Actimates Barney

Robotic Toy that has sensors that interact with light, sound and touch/pressing on the sensors. It also interacts with a certain VHS video tape played on a VCR.

Released in 1997

Discontinued in ~2000 ?

It is a piece of hardware.

**Comment by fabianoriccardi** [comment]
Added https://github.com/fabianoriccardi/killed-by-microsoft/commit/be16f2e71ccb89594ab93432ea0b6a07a3e60dc3

Thanks for the contribution!
