### ISSUE TITLE
No one thinks of Windows 10X?

### ISSUE THREAD

**Issue by suntrise** [fabianoriccardi/killed-by-microsoft#57]
**Windows 10X**

**Windows 10X was considered to be the next Windows.**

**It was never launched.**

**"On May 18, 2021, Head of Windows Servicing and Delivery John Cable stated that Windows 10X had been cancelled, and that its foundational technologies would be leveraged for future Microsoft products."--wikipedia**

**Apps**

**Comment by fabianoriccardi** [comment]
Since it was never released to the public, I wouldn't include it in the graveyard.
