### ISSUE TITLE
Microsoft Amalga - Unified Intelligence System

### ISSUE THREAD

**Issue by giussepe198** [fabianoriccardi/killed-by-microsoft#58]
Microsoft Amalga Unified Intelligence System 
(formerly known as Azyxxi) was a unified health enterprise platform designed to retrieve and display patient ...

https://en.wikipedia.org/wiki/Microsoft_Amalga

**Comment by fabianoriccardi** [comment]
I have read the wiki page and few other sources, however it is seems that Microsoft Amalga wasn't discontinued but sold to [GE Healthcare](https://en.wikipedia.org/wiki/GE_Healthcare). The only product killed by microsoft was Amaga Hospital Information System (HIS) in 2010.

**Comment by fabianoriccardi** [comment]
Amalga HIS added https://github.com/fabianoriccardi/killed-by-microsoft/commit/be16f2e71ccb89594ab93432ea0b6a07a3e60dc3

Thanks for the contribution!
