### ISSUE TITLE
Alive by microsoft

### ISSUE THREAD

**Issue by LifeIsStrange** [fabianoriccardi/killed-by-microsoft#6]
You know what would be even cooler than killed by microsoft? A website Alive by microsoft where we would have a succinct, bullshit free timeline of microsoft product launches.
It's sad but we currently have no clean way of discovering GAFA products without suffering the bloat and non-exhaustivity of their product landing pages.

I mean sure we have https://en.wikipedia.org/wiki/List_of_Microsoft_software
But it's not a timeline and even more importantly there is no description. This is not digest for the brain.
Had this existed I would have discovered Microsoft academic before seeing it on your graveyard..

**Comment by fabianoriccardi** [comment]
> A website Alive by microsoft where we would have a succinct, bullshit free timeline of microsoft product launches.

Nice idea, but not nostalgic as killed by Microsoft could be. I know that wiki link, it is a huge amount of information and it is a great source for this website. In the beginning, when I was launching this website, I thought about a timeline, but I never had the time to develop it, even it is would be a more useful way to display the history.

I never completely abandoned this idea, and [here](https://time.graphics/line/291016) you can see a Microsoft-related timeline I made to test it. If I remember, that website offers an API to integrate those charts into a third-party website...

**Comment by LifeIsStrange** [comment]
Thats a great website I had completely forgotten ! That timeline is visually great!

**Comment by fabianoriccardi** [comment]
Closing since this is the proposal for a new website... Maybe I will add a timeline for Killed by Microsoft.
