### ISSUE TITLE
K

### ISSUE THREAD

**Issue by ChimeraScorn** [fabianoriccardi/killed-by-microsoft#60]
**Kakuto Chojin**

**3D Fighter **

**Novemember 11, 2002 - US, EU, AUS, ::: Jan 1, 2003 - Japan**

****

**App (Xbox Game)*

Recalled in early 2003 and never reissued, due to a song having chanting from the Quaran.  The game was recalled following official protest from Saudi Arabia.  It was never reissued because it was also a commercial and critical failure.

**Comment by fabianoriccardi** [comment]
Added https://github.com/fabianoriccardi/killed-by-microsoft/commit/be16f2e71ccb89594ab93432ea0b6a07a3e60dc3

Thanks for the contribution!
