### ISSUE TITLE
Health Vault Connection Center

### ISSUE THREAD

**Issue by ChimeraScorn** [fabianoriccardi/killed-by-microsoft#62]
**Health Vault Connection Center**

**A client side tool to allow users to upload data from personal health devices to the HealthVault service**

**Oct 7, 2007*

**November 19, 2019**

**App**

**Comment by fabianoriccardi** [comment]
Added in [commit](https://github.com/fabianoriccardi/killed-by-microsoft/commit/8a5027454addbb299fdb27b8d7049e27f5995fe3). Thanks for the contribution!
