### ISSUE TITLE
Sunrise Calendar

### ISSUE THREAD

**Issue by ATChustz** [fabianoriccardi/killed-by-microsoft#64]
**What's the Product's Name?**
Sunrise calendar
**Describe the product in a single sentence.**
Ahead-of-it's-time mobile calendar that was acquired and then absorbed (poorly) into Outlook
**When was the product launched? Provide a specific date, if possible.**
Not sure
**When was the product discontinued? Provide a specific date, if possible.**
Shortly after it was absorbed into Outlook
**What type of product was it? App, Service, OS, or Hardware?**
App

**Comment by adamralph** [comment]
FYI I added this in https://github.com/fabianoriccardi/killed-by-microsoft/pull/67.

(I didn't see this issue until just now.)

**Comment by fabianoriccardi** [comment]
Already merged, thanks to both!
