### ISSUE TITLE
[Typo] under Office Assistant

### ISSUE THREAD

**Issue by JacksonCampbell99** [fabianoriccardi/killed-by-microsoft#65]
<img width="392" alt="image" src="https://user-images.githubusercontent.com/76508020/162046974-7912faaa-8b27-4ebb-95c2-b1ced7d37d7e.png">

The proper article here is `a`.

**Comment by fabianoriccardi** [comment]
Thanks! fixed here https://github.com/fabianoriccardi/killed-by-microsoft/commit/39e221e57a4a1b56c97c996e14bfd33abdd40454
