### ISSUE TITLE
Visual Studio LightSwitch 2011

### ISSUE THREAD

**Issue by mrnoeb** [fabianoriccardi/killed-by-microsoft#66]
Visual Studio Lightswitch

Data-Driven Development Environment, like Access based on Silverlight

30. Oct 2011 - 10. Jan 2017

https://docs.microsoft.com/en-us/lifecycle/products/visual-studio-lightswitch-2011

**Comment by fabianoriccardi** [comment]
Added https://github.com/fabianoriccardi/killed-by-microsoft/commit/16313aabbf3b2a369ff1acdbe9d54a40c5f3f30a

I used a different start date (26-July-2011) as stated in wikipedia and other sources. The date reported on Microsoft web site should refers only to the product "support"...

Thanks for the contribution!
