### ISSUE TITLE
The death sentence date approximations sound weird

### ISSUE THREAD

**Issue by adamralph** [fabianoriccardi/killed-by-microsoft#68]
For killed products it seems you have the following possibilities:

- almost X years
- about X years
- over X years

I.e. you are emphasising how _long ago_ they were killed.

But for sentenced to death products, that doesn't seem to work:

> Sentenced to death in over 3 years, Skype for Business (formerly Microsoft Lync and Office Communicator) was...

(I only see this example now, so I'm not sure what other possibilities exist.)

This sounds weird, because it's emphasising how _far into the future_ something is sentenced to death, whereas I would expect it to emphasise how _soon_ it is, in which case the sentenced to death equivalents of the above list would instead be something like:

- less than X years
- about X years
- just over X years

**Comment by fabianoriccardi** [comment]
Good point, but these words are generated and controlled by `date-fsn` library, and actually there is no the possibility to specify the *shade* of the sentence meaning. 

Of course, it is possible to fix the issue with custom code, but I think time will fix it 😉
