### ISSUE TITLE
Sentenced to death age statements have the incorrect tense

### ISSUE THREAD

**Issue by adamralph** [fabianoriccardi/killed-by-microsoft#69]
E,g

> Skype for Business
>
> Sentenced to death in over 3 years, Skype for Business (formerly Microsoft Lync and Office Communicator) was an enterprise instant messaging software developed by Microsoft as part of the Microsoft Office suite. It was almost 18 years old.

The last sentence is written in the past tense. It should be written in the future tense:

> It will be almost 18 years old.

BTW—I'm not sure if the number stated in this example is the current age or the age at the time of death. It should be the age at the time of death.

**Comment by adamralph** [comment]
BTW—the phrasing should probably be similar to that mentioned in https://github.com/fabianoriccardi/killed-by-microsoft/issues/68:

- will be less than 18 years old
- will be about 18 years old
- will be just over 18 years old

**Comment by fabianoriccardi** [comment]
The years are always counted from begin to end.

Future tense added, thanks for signalling 👍
