### ISSUE TITLE
Sentence to death descriptions have the incorrect tense

### ISSUE THREAD

**Issue by adamralph** [fabianoriccardi/killed-by-microsoft#70]
Similar to https://github.com/fabianoriccardi/killed-by-microsoft/issues/69, but more tricky:

> Skype for Business
>
> Sentenced to death in over 3 years, Skype for Business (formerly Microsoft Lync and Office Communicator) was an enterprise instant messaging software developed by Microsoft as part of the Microsoft Office suite. It was almost 18 years old.

This part is written in the past tense:

> Skype for Business (formerly Microsoft Lync and Office Communicator) was an...

It should be in the present tense:

> Skype for Business (formerly Microsoft Lync and Office Communicator) is an...

**Comment by fabianoriccardi** [comment]
fixed in https://github.com/fabianoriccardi/killed-by-microsoft/commit/c6392533eccbff81459dd7b3aee12aac098791a8. The trick is dirt cheap but it works.
