### ISSUE TITLE
Flight Arcade (Microsoft Edge HTML5 demo)

### ISSUE THREAD

**Issue by mateusza** [fabianoriccardi/killed-by-microsoft#71]
**What's the Product's Name?**

Flight Arcade 
<http://www.flightarcade.com/>

**Describe the product in a single sentence.**

Web browser based clone of Flight Simulator game. Created as a showcase of Microsoft Edge support for modern HTML5 and JavaScript.

**When was the product launched? Provide a specific date, if possible.**

2015 <https://www.windowscentral.com/microsoft-revisits-its-flight-simulator-series-web-based-flight-arcade-game>

First appearance in Wayback Machine is 2015-05-01 <http://web.archive.org/web/20150501000000*/http://www.flightarcade.com/>

**When was the product discontinued? Provide a specific date, if possible.**

The website started to respond after April of 2021.

Last appearance in Wayback Machine is 2021-04-17 <http://web.archive.org/web/20210401000000*/http://www.flightarcade.com/>

**What type of product was it? App, Service, OS, or Hardware?**

Web based game.

**Comment by fabianoriccardi** [comment]
Added https://github.com/fabianoriccardi/killed-by-microsoft/commit/be16f2e71ccb89594ab93432ea0b6a07a3e60dc3

Thanks for the contribution!
