### ISSUE TITLE
Edge is Dead, Long Live Edge

### ISSUE THREAD

**Issue by isaac32767** [fabianoriccardi/killed-by-microsoft#72]
The obit for Edge (EdgeHTML) should mention that it's a different product from Edge (Chromium).

**Comment by fabianoriccardi** [comment]
Yes it was incorrect! I replaced Edge (since edge is actually alive) with EdgeHTML https://github.com/fabianoriccardi/killed-by-microsoft/commit/c7921c18b12058283a6fd2bb6f3ae824a7bffb1d

Thanks for the hint!
