### ISSUE TITLE
Atom editor

### ISSUE THREAD

**Issue by sent44** [fabianoriccardi/killed-by-microsoft#73]
**What's the Product's Name?**
Atom Editor

**Describe the product in a single sentence.**
Hackable editor made by Github

**When was the product launched? Provide a specific date, if possible.**
26 February 2014 (From Google side bar result thing)

**When was the product discontinued? Provide a specific date, if possible.**
Will be archive on [15 December 2022](https://github.blog/2022-06-08-sunsetting-atom/)

**What type of product was it? App, Service, OS, or Hardware?**
App

![Screenshot 2022-06-15 175634](https://user-images.githubusercontent.com/4406577/173812980-ecf11369-ea91-469e-9c18-4f7f28a22c6e.png)

**Comment by mabdelfattah** [comment]
But it was not a Microsoft project :)

**Comment by sent44** [comment]
> But it was not a Microsoft project :)

MSN TV was not (original) [Microsoft product](https://en.wikipedia.org/wiki/MSN_TV#:~:text=developed%20by%20WebTV%20Networks%2C%20Inc), but listed.
Minecraft earth was not (direct) Microsoft product, but listed.

**Comment by pschaub** [comment]
The decision to retire the Atom Editor was published on June 8, 2022 on the linked blog post. At this point, GitHub is owned by Microsoft, so it should be included in the graveyard.

**Comment by fabianoriccardi** [comment]
But it was not a Microsoft project :)

@mabdelfattah Not directly, but for the reasons expressed by the other participants, I will include it!

**Comment by fabianoriccardi** [comment]
Finally added! https://github.com/fabianoriccardi/killed-by-microsoft/commit/a3eacf13537efd3827bfa9ca16df85ac9e4b6f35
