### ISSUE TITLE
Cortana for Consumers

### ISSUE THREAD

**Issue by pschaub** [fabianoriccardi/killed-by-microsoft#75]
Cortana has been mostly removed **for consumers**. It is still partially available in Microsoft 365 for business/enterprise usages.

### Cortana for Xbox

Cortana has been removed from the Xbox in 2019.

Source: https://news.xbox.com/en-us/2019/07/24/new-approaches-to-home-and-xbox-voice-commands-roll-out-to-xbox-insiders/

### Cortona for Windows

> This feature is no longer supported as of the Windows 10 May 2020 Update (version 2004, codename "20H1").

Source: https://docs.microsoft.com/en-us/windows/apps/design/input/cortana-interactions

### Cortona for Mobile
> After March 31, 2021, the Cortana mobile app on your phone will no longer be supported. 

Source: https://support.microsoft.com/en-us/topic/using-cortana-on-ios-or-android-caaa50e4-31f1-4165-9659-3caf125ebd38

**Comment by fabianoriccardi** [comment]
Added https://github.com/fabianoriccardi/killed-by-microsoft/commit/a3eacf13537efd3827bfa9ca16df85ac9e4b6f35 !
I left out Cortana for Windows since the dedicated app still exists.
