### ISSUE TITLE
Age of Empires Online

### ISSUE THREAD

**Issue by Huskynarr** [fabianoriccardi/killed-by-microsoft#76]
**What's the Product's Name?**
Age of Empires Online

**Describe the product in a single sentence.**
The closure of the online game "Age of Empires Online" is due to the fact that the maintenance of the content was too expensive. https://en.wikipedia.org/wiki/Age_of_Empires_Online

**When was the product launched? Provide a specific date, if possible.**
16thAugust 2011

**When was the product discontinued? Provide a specific date, if possible.**
1st July 2014

**What type of product was it? App, Service, OS, or Hardware?**
App

**Comment by fabianoriccardi** [comment]
Added! https://github.com/fabianoriccardi/killed-by-microsoft/commit/d9b8ac5dc78f95d0b2718d4fb8e5b2d65837cccb
