### ISSUE TITLE
Miami Street / Forza Street

### ISSUE THREAD

**Issue by pschaub** [fabianoriccardi/killed-by-microsoft#79]
**What's the Product's Name?**
Miami Street / Forza Street

**Describe the product in a single sentence.**
Miami Street / Forza Street was a free-to-play racing game.

**When was the product launched? Provide a specific date, if possible.**
Miami Street: May 8, 2018
renamed to Forza Street: April 15, 2019

**When was the product discontinued? Provide a specific date, if possible.**
April 11, 2022

**What type of product was it? App, Service, OS, or Hardware?**
Game

**Source**
https://delistedgames.com/forza-street/
https://en.wikipedia.org/wiki/Forza#Forza_Street_(2019%E2%80%932022)

**Comment by fabianoriccardi** [comment]
[Added](https://github.com/fabianoriccardi/killed-by-microsoft/commit/9bc37263181947faa199f10522596a930b2b2a2a)  all your 3 suggestions. Thanks for the contribution!
