### ISSUE TITLE
Products under the Windows Multipoint Mouse brand: Windows MultiPoint Mouse SDK, Windows MultiPoint Server

### ISSUE THREAD

**Issue by nubok** [fabianoriccardi/killed-by-microsoft#8]
**What's the Product's Name?**

Products released under the **Windows Multipoint Mouse** brand:

- **Windows MultiPoint Mouse SDK**
- **Windows MultiPoint Server**

**Describe the product in a single sentence.**

Windows MultiPoint Mouse is a technology that enables the use of multiple pointing devices on the same computer.

(taken from [https://en.wikipedia.org/wiki/Windows_Multipoint_Mouse](https://en.wikipedia.org/wiki/Windows_Multipoint_Mouse))

**When was the product launched? Provide a specific date, if possible.**

**Windows MultiPoint Mouse SDK**: The oldest blog entry of the MultiPoint Blog by Microsoft is from **2007-05-23**: [https://web.archive.org/web/20071117163139/http://blogs.msdn.com/multipoint/default.aspx](https://web.archive.org/web/20071117163139/http://blogs.msdn.com/multipoint/default.aspx)

**Windows MultiPoint Server**: According to [https://en.wikipedia.org/wiki/Windows_MultiPoint_Server](https://en.wikipedia.org/wiki/Windows_MultiPoint_Server): **February 2010**

**When was the product discontinued? Provide a specific date, if possible.**

**Windows MultiPoint Mouse SDK**: The last stable version on [https://web.archive.org/web/20150216031847/http://www.microsoft.com/en-us/download/details.aspx?id=9962](https://web.archive.org/web/20150216031847/http://www.microsoft.com/en-us/download/details.aspx?id=9962) is from **2010-04-22**

**Windows MultiPoint Server**: According to [https://en.wikipedia.org/wiki/Windows_MultiPoint_Server](https://en.wikipedia.org/wiki/Windows_MultiPoint_Server), the last stable version is from **November 2012**.

**What type of product was it? App, Service, or Hardware?**

App

**Comment by fabianoriccardi** [comment]
Thanks for the contribution!

**Comment by fabianoriccardi** [comment]
added https://github.com/fabianoriccardi/killed-by-microsoft/commit/39e221e57a4a1b56c97c996e14bfd33abdd40454
