### ISSUE TITLE
Swype Mobile Keyboard

### ISSUE THREAD

**Issue by martincampbell** [fabianoriccardi/killed-by-microsoft#80]
**What's the Product's Name?**
Swype

**Describe the product in a single sentence.**
Mobile phone keyboard that allowed you to enter whole words by squiggling over the letters without lifting your finger.

**When was the product launched? Provide a specific date, if possible.**
December 2009

**When was the product discontinued? Provide a specific date, if possible.**
February 2018 for new installations, though existing installations could still download new languages until October 2021.

**What type of product was it? App, Service, OS, or Hardware?**
Mobile App

Swype was bought by Nuance. Nuance was bought by Microsoft. The final shutdown happened after the Microsoft acquisition.

**Comment by fabianoriccardi** [comment]
Hi Martin, thanks for the suggestion! 

I think that Nuance has killed Swype in 2018, so Microsoft has just followed what Nuance scheduled in 2018. What do you think?

**Comment by fabianoriccardi** [comment]
Reading from [Wiki](https://en.wikipedia.org/wiki/Swype), Nuance killed Swype in 2018, and only in 2021/2022 Microsoft acquired Nuance. So the *killer* was Nuance and not Microsoft.

**Comment by rbeesley** [comment]
Having worked on the launch team of Swype, this is correct. Nuance bought Swype, killed off Swype, _then_ Microsoft bought Nuance.
