### ISSUE TITLE
Microsoft Hohm

### ISSUE THREAD

**Issue by chencjiajy** [fabianoriccardi/killed-by-microsoft#81]
**What's the Product's Name?**
Microsoft Hohm
**Describe the product in a single sentence.**
a new online application that enables consumers to better understand their energy usage, get recommendations and start saving money
**When was the product launched? Provide a specific date, if possible.**
 June 24, 2009  ,  [reference](https://news.microsoft.com/2009/06/24/microsoft-hohm-helps-consumers-save-money-and-energy/ )
**When was the product discontinued? Provide a specific date, if possible.**
June 30, 2011  , [reference](https://www.cnet.com/culture/microsoft-kills-hohm-energy-app/)
**What type of product was it? App, Service, OS, or Hardware?**
Service

**Comment by fabianoriccardi** [comment]
Added https://github.com/fabianoriccardi/killed-by-microsoft/commit/d9be84bad323ae6d286fdc837cf4937db3abb9b0 

Thanks for the contribution!
