### ISSUE TITLE
Soundscape A Map Delivered in 3D Sound

### ISSUE THREAD

**Issue by uwtcat** [fabianoriccardi/killed-by-microsoft#84]
**What's the Product's Name?**
Soundscape

**Describe the product in a single sentence.**
Microsoft Soundscape was a project from Microsoft Research that explored the use of innovative audio-based technology to enable people to build a richer awareness of their surroundings, thus becoming more confident and empowered to get around, specifically tuned to travelers who are Blind or Visually Impaired.

**When was the product launched? Provide a specific date, if possible.**
2011

**When was the product discontinued? Provide a specific date, if possible.**
December, 2022

**What type of product was it? App, Service, OS, or Hardware?**
App
More information at:
[](https://www.microsoft.com/en-us/research/product/soundscape/)

**Comment by fabianoriccardi** [comment]
Added https://github.com/fabianoriccardi/killed-by-microsoft/commit/d9be84bad323ae6d286fdc837cf4937db3abb9b0 

Thanks for the contribution!
