### ISSUE TITLE
Microsoft branded PC accessories

### ISSUE THREAD

**Issue by SudoQvorum** [fabianoriccardi/killed-by-microsoft#85]
Name of Product (name) - Microsoft Accessories
Launch Date (dateOpen) - 1983
Discontinued Date (dateClose) - May 2023
Description (description) - Microsoft branded keyboards, mice and webcams
Link (link) - https://www.theverge.com/2023/4/27/23700998/microsoft-keyboard-mouse-webcam-discontinued-surface-brand
Links (links) - https://www.techspot.com/news/98497-microsoft-discontinues-branded-pc-accessories-focus-surface-peripherals.html 
Type (type) - Hardware
Slug (slug) - (optional), specify a custom slug (an identifier SEO friendly in the form "product-name"). Used only for testing

**Comment by fabianoriccardi** [comment]
I don't think these products should be placed in the graveyard: they were renewed and rebranded as Surface, that is brand (not a company) owned by Microsoft.
