### ISSUE TITLE
microsoft-kaizala

### ISSUE THREAD

**Issue by rgoldstein1989** [fabianoriccardi/killed-by-microsoft#86]
**What's the Product's Name?**
kaizala
**Describe the product in a single sentence.**
Chat app for events
**When was the product launched? Provide a specific date, if possible.**
June 29, 2019
**When was the product discontinued? Provide a specific date, if possible.**
August 31, 2023
**What type of product was it? App, Service, OS, or Hardware?**
App

Rest in Peace Kaizala

**Comment by fabianoriccardi** [comment]
Added, thanks for the contribution! As release date I prefer 2016, when it was launched in India. https://github.com/fabianoriccardi/killed-by-microsoft/commit/62d052095126b780ec476ead0b6ee465c58dd996
