### ISSUE TITLE
Visual Studio for Mac

### ISSUE THREAD

**Issue by saamerm** [fabianoriccardi/killed-by-microsoft#88]
**What's the Product's Name?**

VS for Mac

**Describe the product in a single sentence.**

A MacOS native application with a subset of features contained in Visual Studio for Windows

**When was the product launched? Provide a specific date, if possible.**

May 2011

**When was the product discontinued? Provide a specific date, if possible.**

August 2024

**What type of product was it? App, Service, OS, or Hardware?**

App

**Comment by fabianoriccardi** [comment]
Added, thanks for the contribution!
