### ISSUE TITLE
WinAppDriver

### ISSUE THREAD

**Issue by ptrthomas** [fabianoriccardi/killed-by-microsoft#90]
Name: WinAppDriver

Description: [Windows Application Driver](https://github.com/microsoft/WinAppDriver) (WinAppDriver) is a service to support Selenium-like UI Test Automation on Windows Applications. This service supports testing Universal Windows Platform (UWP), Windows Forms (WinForms), Windows Presentation Foundation (WPF), and Classic Windows (Win32) apps on Windows 10 PCs.

First Release: [March 30, 2016](https://github.com/microsoft/WinAppDriver/releases/tag/v0.1-beta)

When was it killed: The project was put on "hold" in [November 2020](https://github.com/microsoft/WinAppDriver/issues/1371). The PM surfaced in [July 2020](https://github.com/microsoft/WinAppDriver/issues/1550) with an update that there was no clear timeline for revival. After that it looks like the team is no longer active at Microsoft and all attempts to get an official communication have failed.

Type: App for Automated Testing

**Comment by fabianoriccardi** [comment]
Added, thanks for the suggestion! https://github.com/fabianoriccardi/killed-by-microsoft/commit/75954d3fb1a7777974e11a9a5f7b49221d9c42d0
