### ISSUE TITLE
Minecraft Apple TV Edition

### ISSUE THREAD

**Issue by euroxs** [fabianoriccardi/killed-by-microsoft#91]
**What's the Product's Name?**
Minecraft 

**Describe the product in a single sentence.**
Minecraft Apple TV Edition

**When was the product launched? Provide a specific date, if possible.**
December 19, 2016

**When was the product discontinued? Provide a specific date, if possible.**
September 24, 2018

**What type of product was it? App, Service, OS, or Hardware?**
App

**Comment by fabianoriccardi** [comment]
Added https://github.com/fabianoriccardi/killed-by-microsoft/commit/c45ba7cc8f199c335f8cf51edef5d2f0897cc73a, thanks for the contribution!
