### ISSUE TITLE
Specific Windows Server operating system releases

### ISSUE THREAD

**Issue by pivotman319-owo** [fabianoriccardi/killed-by-microsoft#93]
**What's the Product's Name?**
Hyper-V Server, Windows Server Essentials, Windows Storage Server

**Describe the product in a single sentence.**
- Hyper-V Server: free variant of Windows Server core editions intended for operating system virtualization
- Windows Server Essentials: low-cost edition of Windows Server intended for small businesses; merger of the Windows Home Server, Windows Small Business Server and Windows Essential Business Server product lines
- Windows Storage Server: variant of the Windows Server operating system targeted towards network-attached data storage solutions

**When was the product launched? Provide a specific date, if possible.**
- Hyper-V Server: [product line launched on 1st October 2008](https://web.archive.org/web/20081005171002/www.microsoft.com/presspass/press/2008/oct08/10-01HyperVRTM08PR.mspx)
- Windows Server Essentials: [product line launched on 1st November 2012](https://learn.microsoft.com/en-us/archive/blogs/sbs/windows-server-2012-essentials-releases-to-manufacturing)
- Windows Storage Server: [product line launched on 10th September 2003](https://web.archive.org/web/20030920074052/http://www.microsoft.com/presspass/press/2003/sep03/09-10StorageLaunchPR.asp)

**When was the product discontinued? Provide a specific date, if possible.**
- Hyper-V Server: [Replaced by paid Azure Stack HCI operating system on 10th December 2020](https://azure.microsoft.com/en-us/updates/azure-stack-hci-is-now-generally-available/)
- Windows Server Essentials: [Replaced by Windows Server Standard edition](https://learn.microsoft.com/en-us/windows-server-essentials/get-started/get-started) as part of [Windows Server 2022 public release](https://cloudblogs.microsoft.com/windowsserver/2021/09/01/windows-server-2022-now-generally-available-delivers-innovation-in-security-hybrid-and-containers/); respective edition (`ServerSolution`) removed from Windows source tree during Manganese/Iron dev
- Windows Storage Server: Functionality merged into Windows Server 2019 feature set. Final Storage Server release was Windows Storage Server 2016; respective editions (`ServerStorageStandard(Eval)`, `ServerStorageWorkgroup(Eval)`) removed from Windows source tree during Manganese/Iron dev

**What type of product was it? App, Service, OS, or Hardware?**
Operating system

**Comment by fabianoriccardi** [comment]
Thank you, Windows Server Essentials was already listed, but the other 2 were missing! https://github.com/fabianoriccardi/killed-by-microsoft/commit/23ade1ffde03f95fa50b7ec0e7b3dc026b96c2bf
