### ISSUE TITLE
Microsoft TruePlay

### ISSUE THREAD

**Issue by wTonyChen** [fabianoriccardi/killed-by-microsoft#97]
**What's the Product's Name?**
Microsoft TruePlay

**Describe the product in a single sentence.**
An anti-cheat system by Microsoft.

**When was the product launched? Provide a specific date, if possible.**
Windows 10 Fall Creators Update (introduced in 10.0.16299.0)

**When was the product discontinued? Provide a specific date, if possible.**
As of Windows 10, version 1809 (10.0; Build 17763), this API is removed from the public API surface of Windows.

**What type of product was it? App, Service, OS, or Hardware?**
App

**Comment by fabianoriccardi** [comment]
Added, thanks for the contribution!
