### ISSUE TITLE
Microsoft Virtual Academy

### ISSUE THREAD

**Issue by wTonyChen** [fabianoriccardi/killed-by-microsoft#98]
**What's the Product's Name?**
Microsoft Virtual Academy

**Describe the product in a single sentence.**
A free online training area for Microsoft technologies.

**When was the product launched? Provide a specific date, if possible.**
January 2011

**When was the product discontinued? Provide a specific date, if possible.**
January 31st, 2019

**What type of product was it? App, Service, OS, or Hardware?**
Service

**Comment by fabianoriccardi** [comment]
Can you provide the reference links about open and close dates?

**Comment by wTonyChen** [comment]
> Can you provide the reference links about open and close dates?

Retiring phases beginning on Jan 31, 2019 (according to this notice): 
https://web.archive.org/web/20181213143909/https://mva.microsoft.com/

MVA retiring on Jun 10, 2019 (according to this notice): https://web.archive.org/web/20190513154350/https://mva.microsoft.com/

Opening date's little bit unclear, the official Twitter account was created on Jan 2011:
https://twitter.com/MSVirtAcademy

**Comment by fabianoriccardi** [comment]
Done!
